ProyectoFinal/ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("base.urls")),
    path('', include("autentifications.urls")),
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ProyectoFinal/base/urls.py
from django.urls import path
from base.views import *

urlpatterns = [
    path("", view_home),
    path("about/", view_about),
    path("list_lb/", view_list_lb),
    path("menu/infoprod/delete/<path:modelo>/", view_infodelete),
    path("list_electro/", view_list_electro),
    path("list_info/", view_list_info),
    path("infoprod/<path:modelo>/", view_infoprod), #el path: es para que me acepte los modelos que tengan /
    path("menu/", view_menu, name="menu"),
    path("menu/infoprod/edit/<path:modelo>/", view_infoprod_edit),
    path("menu/newproduct/", CrearProductoView),
    path("menu/productlist/", ProductoView, name="productlist"),
    path("menu/editproduct/<int:id>/", ModificarProductoView, name="edit-product"),
    path("menu/deleteproduct/<int:id>/", BorrarProductoView, name="delete-product"),    
    path("menu/newinfo/", CrearInfoView,name="new-info"),
    path("menu/infoprod/<path:modelo>/", view_infoprod_admin),
    path("menu/ingresocompras/", view_ingresar_compra),
    path("menu/vercompras/", view_ver_compras),
    path("menu/vercomprasadmin/", view_ver_compras_admin),
    path("menu/edit_profile/", view_editar_perfil),
    path("menu/view_profile/", view_perfil),
    path("menu/edit_avatar/", view_avatar),
    path("menu/new_blog/", view_crear_blog),
    path("menu/all_blogs_admin/", view_ver_blogs_admin),
    path("pages/", view_ver_blogs),
    path("menu/detailblog_admin/<int:id>/", view_detailblog_admin, name="detailblog_admin"),
    path("pages/<int:id>/", view_detailblog, name="blog_detalle"),
    path("menu/editblog/<int:id>/", view_edit_blog, name="edit-blog"),
    path("menu/deleteblog/<int:id>/", view_deleteblog, name="borrar-blog"),
    path("menu/detailblog_admin/<int:id>/newpost/", view_crear_post, name="newpost"),
    path("menu/detailblog_admin/<int:id>/view_posts_admin/", view_verposts_admin, name="viewposts_admin"),
    path("pages/<int:id>/view_posts", view_verposts, name="viewposts"),
    path("menu/detailblog_admin/editpost/<int:id>", view_editar_post, name="editpost"),
    path("menu/detailblog_admin/deletepost/<int:id>", view_deletepost, name="deletepost"),
    path("pages/<int:id>/comments", view_ver_comentarios, name="comments"),
    path("newcomment/<int:id>", view_crear_comentario, name="newcomment"),
]

ProyectoFinal/base/models.py
from django.db import models
from django.contrib.auth.forms import UserModel
from django.contrib.auth.models import User

category=(
    (1, 'Línea Blanca'),
    (2, 'Electro'),
    (3, 'Informática'),
)

prov=(
    (1, 'Buenos Aires'),
    (2, 'C.A.B.A.'),
    (3, 'Catamarca'),
    (4, 'Chaco'),
    (5, 'Chubut'),
    (6, 'Córdoba'),
    (7, 'Corrientes'),
    (8, 'Entre Ríos'),
    (9, 'Formosa'),
    (10, 'Jujuy'),
    (11, 'La Pampa'),
    (12, 'La Rioja'),
    (13, 'Mendoza'),
    (14, 'Misiones'),
    (15, 'Neuquén'),
    (16, 'Río Negro'),
    (17, 'Salta'),
    (18, 'San Juan'),
    (19, 'San Luis'),
    (20, 'Santa Cruz'),
    (21, 'Santa Fe'),
    (22, 'Santiago del Estero'),
    (23, 'Tierra del Fuego'),
    (24, 'Tucumán'),
    (25, 'Islas Malvinas'),
)

class UpperField(models.CharField): #INTERVENGO CHARFIELD PARA QUE ME LO TOME EN MAYÚSCULA
    def get_prep_value(self, value):
        return str(value).upper()

class Producto(models.Model):
    modelo = UpperField(max_length=100, unique=True)
    producto = UpperField(max_length=100)
    categoria = models.IntegerField(choices=category)
    marca = UpperField(max_length=100)
    precio = models.DecimalField(decimal_places=2, max_digits=9)

    def __str__(self):
        return self.modelo
    
class InfoProd(models.Model):
    modelo = models.OneToOneField(Producto, on_delete=models.CASCADE) #CUANDO BORRO EL PRODUCTO, QUE BORRE LA RESEÑA
    titulo = models.CharField(max_length=100, blank=False, null=False)
    cuerpo = models.TextField()
    imagen = models.FileField(upload_to="productos")

    def __str__(self):
        return f"Info {self.modelo}"
    
class Compras(models.Model):
    usuario = models.ForeignKey(UserModel, null=True, on_delete=models.SET_NULL)
    fecha_compra = models.DateField()
    producto = models.ForeignKey(Producto, null=True, on_delete=models.SET_NULL)
    dir_envio = UpperField(max_length=1000)
    provincia_envio = models.IntegerField(choices=prov)

    def __str__(self):
        return f"Compra {self.usuario} {self.producto}"
    
class Avatar(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.FileField(upload_to="avatares", null=True, blank=True)

    def __str__(self):
        return f"Avatar {self.user}"
    
class Blog(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)                   #CUANDO BORRO EL ADMIN, QUE NO VA A PASAR, QUE BORRE EL BLOG
    titulo = UpperField(max_length=100)
    subtitulo = models.CharField(max_length=200)
    fecha = models.DateField()
    descripcion = models.CharField(max_length=2000)

    def __str__(self):
        return f"{self.titulo}"
    
class Post(models.Model):                                                                   #el autor siempre es admin
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)                    #CUANDO BORRO EL ADMIN, QUE NO VA A PASAR, QUE BORRE EL POST
    titulo = UpperField(max_length=100)
    subtitulo = models.CharField(max_length=200)
    fecha = models.DateField()    
    cuerpo = models.TextField()
    imagen = models.FileField(upload_to="posts")

    def __str__(self):
        return f"{self.titulo}"

class Comentario(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)                   #CUANDO BORRO EL USER, QUE BORRE EL COMMENT
    post = models.ForeignKey(Post, on_delete=models.CASCADE)                    #CUANDO BORRO EL POST, QUE BORRE EL COMMENT
    fecha = models.DateField()    
    comentario = models.TextField()

    def __str__(self):
        return f"@{self.autor}: '{self.post}'"

ProyectoFinal/base/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from datetime import date
from . import models, forms
from django.contrib.auth.models import User

ruta=None

def date_format(date):
    months = ("Enero", "Febrero", "Marzo", "Abri", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre")
    day = date.day
    month = months[date.month - 1]                                  
    year = date.year
    return f"{day} de {month} de {year}"

def view_home(request):
    if request.user.is_authenticated:
        usuario = request.user
        avatar = models.Avatar.objects.filter(user=usuario).last()
        avatar_url = avatar.imagen.url if avatar is not None else ""
    else:
        avatar_url = ""
    nombre = "Bruno"
    apellido = "Salerno"
    fecha = date_format(date.today())
    diccionario = {
        'nombre': nombre,
        'apellido': apellido,
        'fecha': fecha,
        'avatar_url': avatar_url
    }  # Para enviar al contexto
    return render(request, "base/home.html", diccionario)

def view_about(request):
    if request.user.is_authenticated:
        usuario = request.user
        avatar = models.Avatar.objects.filter(user=usuario).last()
        avatar_url = avatar.imagen.url if avatar is not None else ""
    else:
        avatar_url = ""
    diccionario = {
        'avatar_url': avatar_url,
    }
    return render(request, "base/about.html", diccionario)

def view_list_lb(request):
    producto_filtrado = []
    for producto in models.Producto.objects.filter(categoria="1"):
        producto_filtrado.append(producto)
    if request.user.is_authenticated:
        usuario = request.user
        avatar = models.Avatar.objects.filter(user=usuario).last()
        avatar_url = avatar.imagen.url if avatar is not None else ""
    else:
        avatar_url = ""
    diccionario = {
        'avatar_url': avatar_url,
        "productos": producto_filtrado,
    }
    return render(request, "base/verproductos.html", diccionario)

def view_list_electro(request):
    producto_filtrado = []
    for producto in models.Producto.objects.filter(categoria="2"):
        producto_filtrado.append(producto)
    if request.user.is_authenticated:
        usuario = request.user
        avatar = models.Avatar.objects.filter(user=usuario).last()
        avatar_url = avatar.imagen.url if avatar is not None else ""
    else:
        avatar_url = ""
    diccionario = {
        'avatar_url': avatar_url,
        "productos": producto_filtrado,
    }
    return render(request, "base/verproductos.html", diccionario)

def view_list_info(request):
    producto_filtrado = []
    for producto in models.Producto.objects.filter(categoria="3"):
        producto_filtrado.append(producto)
    if request.user.is_authenticated:
        usuario = request.user
        avatar = models.Avatar.objects.filter(user=usuario).last()
        avatar_url = avatar.imagen.url if avatar is not None else ""
    else:
        avatar_url = ""
    diccionario = {
        'avatar_url': avatar_url,
        "productos": producto_filtrado,
    }
    return render(request, "base/verproductos.html", diccionario)

def view_infoprod(request, modelo):
    modelo=modelo[1:-1]
    aux = get_object_or_404(models.Producto,modelo=modelo)
    id = aux.pk
    info = []
    for x in models.InfoProd.objects.filter(modelo=id):
        info.append(x)
    if request.user.is_authenticated:
        usuario = request.user
        avatar = models.Avatar.objects.filter(user=usuario).last()
        avatar_url = avatar.imagen.url if avatar is not None else ""
    else:
        avatar_url = ""
    diccionario = {
        'avatar_url': avatar_url,
        "descripcion": info,
    }
    return render(request, "base/infoprod.html", diccionario)

@login_required
def view_menu(request):
    if request.user.is_authenticated:
        usuario = request.user
        avatar = models.Avatar.objects.filter(user=usuario).last()
        avatar_url = avatar.imagen.url if avatar is not None else ""
    else:
        avatar_url = ""
    diccionario = {
        'avatar_url': avatar_url,
    }
    if (request.user.is_superuser):
        return render(request, "base/adminmenu.html", diccionario)
    else:
        return render(request, "base/usermenu.html", diccionario)

@login_required    
def CrearProductoView(request):
    if request.method == "POST":
        form = forms.ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Producto ingresado.")
            return redirect("productlist")
        else:
            messages.error(request, "Intentelo nuevamente en unos minutos.")
            return redirect("/menu/newproduct")
    else:
        form = forms.ProductoForm()
        if request.user.is_authenticated:
            usuario = request.user
            avatar = models.Avatar.objects.filter(user=usuario).last()
            avatar_url = avatar.imagen.url if avatar is not None else ""
        else:
            avatar_url = ""
        diccionario = {
            'avatar_url': avatar_url,
            "form": form,
        }
    return render(request, "base/crear_producto.html", diccionario)

@login_required
def ProductoView(request):
    productos = []
    for i in models.Producto.objects.all():
        productos.append(i)
    if request.user.is_authenticated:
        usuario = request.user
        avatar = models.Avatar.objects.filter(user=usuario).last()
        avatar_url = avatar.imagen.url if avatar is not None else ""
    else:
        avatar_url = ""
    diccionario = {
        'avatar_url': avatar_url,
        "productos": productos,
        }
    return render(request, "base/lista_productos.html", diccionario)

@login_required
def ModificarProductoView(request, id):
    product = models.Producto.objects.get(id=id)
    if request.method == 'POST':
        form = forms.ProductoEditForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            product.modelo = product.modelo
            product.producto = data["producto"]
            product.categoria = data["categoria"]
            product.marca = data["marca"]
            product.precio = data["precio"]  
            product.save()
            messages.success(request, "Producto modificado.")
            return redirect("productlist")
        else:
            messages.error(request, "Intentelo nuevamente en unos minutos.")
            return redirect("productlist")
    else:
        form = forms.ProductoEditForm(initial={"producto": product.producto,"categoria": product.categoria,"marca": product.marca,"precio": product.precio})
        if request.user.is_authenticated:
            usuario = request.user
            avatar = models.Avatar.objects.filter(user=usuario).last()
            avatar_url = avatar.imagen.url if avatar is not None else ""
        else:
            avatar_url = ""
        diccionario = {
            'avatar_url': avatar_url,
            "form": form,
            "id": product.id
            }
        return render(request, "base/update_producto.html", diccionario)

@login_required
def BorrarProductoView(request, id):
    if request.method == 'POST':
        product = models.Producto.objects.get(id=id)
        product.delete()
        messages.success(request, "Producto eliminado.")
        return redirect("productlist")
    else:
        if request.user.is_authenticated:
            usuario = request.user
            avatar = models.Avatar.objects.filter(user=usuario).last()
            avatar_url = avatar.imagen.url if avatar is not None else ""
        else:
            avatar_url = ""
        diccionario = {
            'avatar_url': avatar_url,
            }
        return render(request, "base/borrar_producto.html", diccionario)

@login_required
def CrearInfoView(request):
    if request.method == "POST":
        form = forms.InfoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Reseña ingresada.")
            return redirect("productlist")
        else:
            messages.error(request, "Intentelo nuevamente en unos minutos.")
            return redirect("productlist")
    else:
        form = forms.InfoForm()
        if request.user.is_authenticated:
            usuario = request.user
            avatar = models.Avatar.objects.filter(user=usuario).last()
            avatar_url = avatar.imagen.url if avatar is not None else ""
        else:
            avatar_url = ""
        diccionario = {
            'avatar_url': avatar_url,
            "form": form,
        }
    return render(request, "base/crear_info.html", diccionario)

@login_required
def view_infoprod_admin(request, modelo):
    modelo=modelo[1:-1]
    aux = get_object_or_404(models.Producto,modelo=modelo)
    id = aux.pk
    info = []
    for x in models.InfoProd.objects.filter(modelo=id):
        info.append(x)
    if request.user.is_authenticated:
        usuario = request.user
        avatar = models.Avatar.objects.filter(user=usuario).last()
        avatar_url = avatar.imagen.url if avatar is not None else ""
    else:
        avatar_url = ""
    diccionario = {
        'avatar_url': avatar_url,
        "descripcion": info,
    }
    return render(request, "base/infoprod_admin.html", diccionario)

@login_required
def view_infoprod_edit(request,modelo):
    modelo=modelo[1:-1]
    aux = get_object_or_404(models.Producto,modelo=modelo)
    id = aux.pk
    info = get_object_or_404(models.InfoProd,modelo=id)
    imagen = info.imagen
    valores_iniciales = {"titulo": info.titulo, "cuerpo": info.cuerpo, "imagen": info.imagen}
    if request.method == 'POST':
        form = forms.EditInfoForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data

ProyectoFinal/base/templates/base/about.html
{% extends "base/navbar.html" %}

{% block content %}
{% load static %}
<!-- Page content-->
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
                <article>
                    <header class="mb-4">
                        <h1 class="fw-bolder mb-1">Acerca de mí</h1>
                    </header>
                    <!-- Preview image figure-->
                    <figure class="mb-4"><img class="img-fluid rounded" src="{% static 'base/assets/img/about.png' %}" alt="..." /></figure>
                    <!-- Post content-->
                    <section class="mb-5">
                        <p class="fs-5 mb-4">Mi nombre es Bruno Salerno. Soy argentino, de Boca, fanático de Chevrolet y profundamente rosista. Nací en Marzo de 1989, en plena hiperinflación en Argentina.</p>
                        <p class="fs-5 mb-4">Soy Ingeniero Electrónico recibido en 2015, en la gloriosa Universidad Tecnológica Nacional (UTN), previamente Universidad Obrera Nacional (fundada en 1948 por el Teniente General Juan Domingo Perón).</p>
                        <p class="fs-5 mb-4"><i>"No queremos universidades para formar charlatanes y generalizadores. No queremos escuelas para formar hombres que les digan a los demás cómo hay que hacer las cosas sino hombres que sepan hacer por sí las cosas (...) y para esto hay que tener manos de trabajador y vivir con olor a aceite de las máquinas".</i></p>
                        <p class="fs-5 mb-4">Hablo y escribo en idioma inglés, obteniendo la certificación First Certificate en 2006. En 2022 finalicé con éxito un curso de Posgrado en Dirección de Recursos Humanos en UADE, y en 2023 realicé un curso de PowerBI en CoderHouse, también satisfactoriamente. Tengo conocimientos en reparación de PC, adquiridos de forma autodidacta.</p>
                        <p class="fs-5 mb-4">Mis expectativa con Python es conocer las bases del lenguaje, para en un futuro posiblemente poder adentrarme en el mundo de la Inteligencia Artificial, la cuál claramente es el futuro y reemplazará a muchos de los trabajos actuales.</p>
                    </section>
                </article>
        </div>
    </div>
</div>
{% endblock content %}

ProyectoFinal/base/templates/base/adminmenu.html
{% extends "base/navbar.html" %}

{% block content %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </ul>
    {% endif %}
    <br><br>
    <h1>Menu de usuario de Admin</h1>
    <br><br>
    <div class="d-grid gap-2 col-6 mx-auto">
        <button class="btn btn-primary" type="button" onclick="location.href='/menu/view_profile'">Ver perfil</button>
        <button class="btn btn-info" type="button" onclick="location.href='/menu/productlist'">Ver productos</button>
        <button class="btn btn-warning" type="button" onclick="location.href='/menu/vercomprasadmin'">Ver Compras</button>
        <button class="btn btn-success" type="button" onclick="location.href='/menu/new_blog'">Crear Blog</button>
        <button class="btn btn-info" type="button" onclick="location.href='/menu/all_blogs_admin'">Ver Blogs</button>
    </div>
{% endblock content %}

ProyectoFinal/base/templates/base/borrar_blog.html
{% extends "base/navbar.html" %}

{% block content %}

<style>
    .centered-container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        height: 100vh;
    }

    .warning-message {
        background-color: #ffcccb;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        text-align: center;
        margin-bottom: 20px;
    }

    .warning-message h1 {
        color: red;
    }

    .warning-message p {
        font-size: 18px;
    }

    .submit-button {
        background-color: red;
        color: white;
        border: none;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 8px;
    }
</style>

<div class="centered-container">
    {{ nombre }}
    <div class="warning-message">
        <h1>Borrar Blog</h1>
        <p>Estás seguro que deseas borrar el blog?</p>
    </div>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Eliminar" class="submit-button">
    </form>
</div>

{% endblock %}

ProyectoFinal/base/templates/base/borrar_info.html
{% extends "base/navbar.html" %}

{% block content %}

<style>
    .centered-container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        height: 100vh;
    }

    .warning-message {
        background-color: #ffcccb;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        text-align: center;
        margin-bottom: 20px;
    }

    .warning-message h1 {
        color: red;
    }

    .warning-message p {
        font-size: 18px;
    }

    .submit-button {
        background-color: red;
        color: white;
        border: none;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 8px;
    }
</style>

<div class="centered-container">
    {{ nombre }}
    <div class="warning-message">
        <h1>Borrar reseña</h1>
        <p>Estás seguro que deseas borrar la reseña?</p>
    </div>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Eliminar" class="submit-button">
    </form>
</div>

{% endblock %}

ProyectoFinal/base/templates/base/borrar_producto.html
{% extends "base/navbar.html" %}

{% block content %}

<style>
    .centered-container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        height: 100vh;
    }

    .warning-message {
        background-color: #ffcccb;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        text-align: center;
        margin-bottom: 20px;
    }

    .warning-message h1 {
        color: red;
    }

    .warning-message p {
        font-size: 18px;
    }

    .submit-button {
        background-color: red;
        color: white;
        border: none;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 8px;
    }
</style>

<div class="centered-container">
    {{ nombre }}
    <div class="warning-message">
        <h1>Borrar producto</h1>
        <p>Estás seguro que deseas borrar el producto?</p>
    </div>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Eliminar" class="submit-button">
    </form>
</div>

{% endblock %}

ProyectoFinal/base/templates/base/crear_info.html
{% extends 'base/navbar.html' %}
{% load crispy_forms_tags %}

{% block content %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </ul>
    {% endif %}
    <br><br>
    <h1>Crear Reseña</h1>
    <br><br>
    <h3>Recuerde que no puede crear una reseña de un modelo que ya la tiene.</h3>
    <br><br>
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">Crear</button>
        <br><br>
        <p>* Campo requerido</p>
    </form>
{% endblock %}

ProyectoFinal/base/templates/base/crear_producto.html
{% extends 'base/navbar.html' %}
{% load crispy_forms_tags %}

{% block content %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </ul>
    {% endif %}
    <br><br>
    <h1>Crear Producto</h1>
    <br><br>
    <h3>Recuerde que no puede crear un producto con un modelo ya existente.</h3>
    <br><br>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">Crear</button>
        <br><br>
        <p>* Campo requerido</p>
    </form>
{% endblock %}

ProyectoFinal/base/templates/base/editpost.html
{% extends 'base/navbar.html' %}
{% load crispy_forms_tags %}

{% block content %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </ul>
    {% endif %}
    <br><br>
    <h1>Editar Post</h1>
    <br><br>
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">Guardar</button>
        <br><br>
        <p>* Campo requerido</p>
    </form>
{% endblock %}

ProyectoFinal/base/templates/base/ingresocompras.html
{% extends "base/navbar.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </ul>
    {% endif %}
    <br><br>
    <h1>Ingreso de compra</h1>
    <br><br>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">Guardar</button>
        <br><br>
        <p>* Campo requerido</p>
    </form>
{% endblock content %}

ProyectoFinal/base/templates/base/newblog.html
{% extends 'base/navbar.html' %}
{% load crispy_forms_tags %}

{% block content %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </ul>
    {% endif %}
    <br><br>
    <h1>Crear Blog</h1>
    <br><br>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">Crear</button>
        <br><br>
        <p>* Campo requerido</p>
    </form>
{% endblock %}

ProyectoFinal/base/templates/base/newcomment.html
{% extends 'base/navbar.html' %}
{% load crispy_forms_tags %}

{% block content %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </ul>
    {% endif %}
    <br><br>
    <h1>Ingresar comentario</h1>
    <br><br>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">Comentar</button>
        <br><br>
        <p>* Campo requerido</p>
    </form>
{% endblock %}

ProyectoFinal/base/templates/base/update_producto.html
{% extends 'base/navbar.html' %}
{% load crispy_forms_tags %}

{% block content %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </ul>
    {% endif %}
    <br><br>
    <h1>Modificar Producto</h1>
    <br><br>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">Guardar</button>
        <br><br>
        <p>* Campo requerido</p>
    </form>
{% endblock %}

ProyectoFinal/base/templates/base/vercompras.html
{% extends "base/navbar.html" %}
{% block content %}
    <br><br>
    <h1>Compras</h1>
    <br><br>
    {% if compras %}
        <table class="table table-success table-striped">
            <thead>
                <th>Fecha de compra</th>
                <th>Producto</th>
                <th>Dirección de envío</th>
                <th>Provincia de envío</th>            
            </thead>
            <tbody>
                {% for compra in compras %}
                    <tr>
                        <td>{{compra.fecha_compra}}</td>
                        <td>{{compra.producto}}</td>
                        <td>{{compra.dir_envio}}</td>
                        <td>{{compra.get_provincia_envio_display}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        {% load static %}
        <figure class="mb-4"><div style="text-align: center;"><img class="img-fluid rounded" src="{% static 'base/assets/img/notfound.png' %}" alt="..." /></figure></div>
        <br><br>
        <div style="text-align: center;"><h1>UPS! No hay nada que mostrar aún</h1></div>
    {% endif %}   
{% endblock content %}